name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    continue-on-error: true  
    strategy:
      matrix:
        mpi: [mpich, openmpi] # Test with both MPI implementations
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: ${{ matrix.mpi }}

    - name: Install Fortran Compiler
      run: sudo apt-get install -y gfortran

    - name: Build Model A
      run: |
        cd model_A
        mpif90 -std=gnu main.f90 -O2 -o main
    
    - name: Test Model A
      run: |
        cd model_A
        mpirun -np 2 ./main
